### ISSUE TITLE
rename/move repo to dlang-tour

### ISSUE THREAD

**Issue by wilzbach** [dlang-tour/dlang-tour#459]
Maybe `master` or `base`?

The `.travis.yml` files of the language reposititories should be updated (Github has redirects, so this doesn't block at all)

(part of #454)

**Comment by stonemaster** [comment]
Or `core`? I would just rule out `master` because it is a reserved term of Git so this might be confusing. I am note yet sure..

**Comment by wilzbach** [comment]
> Or core? I would just rule out master because it is a reserved term of Git so this might be confusing. I am note yet sure..

"master" was just a pun, because it's part of the current name. Feel free to pick any name - I don't mind ;-)

**Comment by stonemaster** [comment]
Let's go with `base`. We just have to empty the PR queue before that move :-)

**Comment by wilzbach** [comment]
> Let's go with base. We just have to empty the PR queue before that move :-)

No need - you can simply go to settings and move the repo over to dlang-tour. It's called "Transfer ownership".

**Comment by wilzbach** [comment]
> No need - you can simply go to settings and move the repo over to dlang-tour. It's called "Transfer ownership".

Ping @stonemaster - simply go to https://github.com/stonemaster/dlang-tour/settings and to the transfer

**Comment by stonemaster** [comment]
Just transfered both the tour and `-rdmd` repositories to the organization. Hopefully everything works as usual :-)

**Comment by wilzbach** [comment]
Thanks a lot!

**Comment by ZombineDev** [comment]
Much appreciated @stonemaster!
