### ISSUE TITLE
Implement dpaste execution driver

### ISSUE THREAD

**Issue by stonemaster** [dlang-tour/dlang-tour#60]
A new paste execution driver which uses dpaste.org to compile and run code samples.

**Comment by wilzbach** [comment]
@stonemaster if you do this in JS, you might want to have a look at https://github.com/dlang/dlang.org/pull/1297. If @nazriel whitelists tour.dlang.org (and tour.dlang.io) for CORS requests, it's a simple POST request ;-)

**Comment by stonemaster** [comment]
The execution driver should better be implemented inside the vibe.d core like the other execution drivers. This should be transparent for the frontend. So CORS shouldn't matter then. But yeah it should be just a simple POST request :-)

**Comment by nazriel** [comment]
Once I'm done with new dpaste backend (should be days now) I will simply make pull request with new execution driver (if you don't mind of course).

I agree with @stonemaster that we probably should use requests via backend so we have unified interface for execution drivers - making an exception just for dpaste (and using Cross-Ajax request) doesn't seem consistent.

**Comment by stonemaster** [comment]
@nazriel No I don't mind :-) Sounds like a cool new feature.

**Comment by wilzbach** [comment]
It seems like this is never going to happen and as unfortunately DPaste isn't really moving forward I guess we should better close this and maybe once a new DPaste comes along reopen this.

@nazriel feel free to ping us anytime when you have updates on DPaste ;-)
